"""add_missing_indexes_and_column

Revision ID: 68faad5cf8bf
Revises: 010846f01f3e
Create Date: 2026-02-19 01:11:24.715374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '68faad5cf8bf'
down_revision: Union[str, Sequence[str], None] = '010846f01f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_client_id', 'audit_logs', ['client_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_resource_type', 'audit_logs', ['resource_type'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.add_column('conversations', sa.Column('channel_conversation_id', sa.String(length=255), nullable=True))
    op.create_index('ix_conversations_client_id', 'conversations', ['client_id'], unique=False)
    op.create_index('ix_conversations_is_active', 'conversations', ['is_active'], unique=False)
    op.create_index('ix_conversations_lead_id', 'conversations', ['lead_id'], unique=False)
    op.alter_column('escalations', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index('ix_escalations_created_at', 'escalations', ['created_at'], unique=False)
    op.alter_column('knowledge_bases', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index('ix_knowledge_bases_category', 'knowledge_bases', ['category'], unique=False)
    op.alter_column('knowledge_chunks', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index('ix_leads_client_id', 'leads', ['client_id'], unique=False)
    op.create_index('ix_leads_client_status', 'leads', ['client_id', 'status'], unique=False)
    op.create_index('ix_leads_created_at', 'leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=False)
    op.create_index('ix_leads_score', 'leads', ['score'], unique=False)
    op.create_index('ix_leads_status', 'leads', ['status'], unique=False)
    op.create_index('ix_messages_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('ix_messages_role', 'messages', ['role'], unique=False)
    op.alter_column('qualification_rules', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index('ix_qualification_rules_category', 'qualification_rules', ['category'], unique=False)
    op.create_index('ix_qualification_rules_is_active', 'qualification_rules', ['is_active'], unique=False)
    op.alter_column('rate_limit_records', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index('ix_rate_limit_window', 'rate_limit_records', ['window_start', 'window_end'], unique=False)
    op.alter_column('usage_logs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index('ix_usage_logs_client_created', 'usage_logs', ['client_id', 'created_at'], unique=False)
    op.create_index('ix_user_sessions_expires_at', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('ix_user_sessions_is_valid', 'user_sessions', ['is_valid'], unique=False)
    op.create_index('ix_user_sessions_refresh_token_hash', 'user_sessions', ['refresh_token_hash'], unique=False)
    op.create_index('ix_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_index('ix_users_client_id', 'users', ['client_id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_client_id', table_name='users')
    op.drop_index('ix_user_sessions_user_id', table_name='user_sessions')
    op.drop_index('ix_user_sessions_refresh_token_hash', table_name='user_sessions')
    op.drop_index('ix_user_sessions_is_valid', table_name='user_sessions')
    op.drop_index('ix_user_sessions_expires_at', table_name='user_sessions')
    op.drop_index('ix_usage_logs_client_created', table_name='usage_logs')
    op.alter_column('usage_logs', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_rate_limit_window', table_name='rate_limit_records')
    op.alter_column('rate_limit_records', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_qualification_rules_is_active', table_name='qualification_rules')
    op.drop_index('ix_qualification_rules_category', table_name='qualification_rules')
    op.alter_column('qualification_rules', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_messages_role', table_name='messages')
    op.drop_index('ix_messages_created_at', table_name='messages')
    op.drop_index('ix_messages_conversation_id', table_name='messages')
    op.drop_index('ix_leads_status', table_name='leads')
    op.drop_index('ix_leads_score', table_name='leads')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index('ix_leads_created_at', table_name='leads')
    op.drop_index('ix_leads_client_status', table_name='leads')
    op.drop_index('ix_leads_client_id', table_name='leads')
    op.alter_column('knowledge_chunks', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_knowledge_bases_category', table_name='knowledge_bases')
    op.alter_column('knowledge_bases', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_escalations_created_at', table_name='escalations')
    op.alter_column('escalations', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_conversations_lead_id', table_name='conversations')
    op.drop_index('ix_conversations_is_active', table_name='conversations')
    op.drop_index('ix_conversations_client_id', table_name='conversations')
    op.drop_column('conversations', 'channel_conversation_id')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource_type', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_client_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    # ### end Alembic commands ###
